board/urls.py
from django.urls import path

from .views import AboutPageView, HomePageView

app_name = 'board'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import include, path
from django.views.generic import TemplateView

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/',
         views.SignUp.as_view(),
         name='signup'),  # регистрация новых пользователей
    path('signup/confirm_your_email/',
         TemplateView.as_view(template_name='registration/confirm_page.html'),
         name='confirmation_page'),  # сообщение о ссылке-подтверждении
    path('signup/<uuid:uuid>/',
         views.email_confirm,
         name='email_confirm'),  # переход по ссылке-подтверждению
    path('login/',
         views.CustomLoginView.as_view(),
         name='login'),  # вход зарегистрированных активых пользователей
    path('password_reset/',
         views.CustomPasswordResetView.as_view(),
         name='password_reset'),  # запрос на восстановление пароля
    path('reset/<uidb64>/<token>/',
         views.CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),  # подтверждение восстановления пароля
    path('', include('django.contrib.auth.urls')),
]

board/models.py
from django.db import models

# Create your models here.

users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
# для интернационализации
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    """Кастомная модель пользователя доски объявлений"""
    USER = 'user'
    MODERATOR = 'moderator'
    ADMIN = 'admin'
    ROLE_CHOICES = (
        (USER, 'пользователь'),
        (MODERATOR, 'модератор'),
        (ADMIN, 'администратор'),
    )
    username = None
    uuid = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
    )
    first_name = models.CharField(
        max_length=50,
        verbose_name=_('имя'),
    )
    last_name = models.CharField(
        max_length=50,
        verbose_name=_('фамилия'),
    )
    middle_name = models.CharField(
        max_length=50,
        blank=True,
        verbose_name=_('отчество'),
    )
    role = models.CharField(
        max_length=20,
        choices=ROLE_CHOICES,
        default=USER,
        verbose_name=_('роль'),
    )
    email = models.EmailField(
        blank=False,
        unique=True,
        verbose_name='email'  # Не локализуем, общепринятое в мире обозначение
    )
    phone_number = models.CharField(
        max_length=10,
        blank=False,
        unique=True,
        verbose_name=_('телефонный номер'),
    )
    call_reception_time = models.CharField(
        max_length=255,
        verbose_name=_('Удобное время приема звонков'),
    )
    is_active = models.BooleanField(
        default=False,
        verbose_name=_('Статус активации'),
    )

    objects = CustomUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone_number']

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CustomSignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = (
            'email',
            'phone_number',
            'last_name',
            'first_name',
            'middle_name',
            'call_reception_time',
        )

board/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'home.html'


class AboutPageView(TemplateView):
    template_name = 'about.html'

users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import views as auth_views
from django.core.mail import EmailMessage
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomSignupForm


class SignUp(CreateView):
    """Регистрация с активацией аккаунта через email"""
    form_class = CustomSignupForm
    success_url = reverse_lazy('users:confirmation_page')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        self.object = form.save()
        email = EmailMessage(
            subject='Перейдите по ссылке для окончания регистрации на сайте',
            body=self.request.build_absolute_uri(self.object.uuid),
            to=[self.object.email],
        )
        email.send(fail_silently=True)
        return super().form_valid(form)


def email_confirm(request, uuid):
    new_user = get_object_or_404(get_user_model(), uuid=uuid)
    new_user.is_active = True
    new_user.save()
    messages.success(request, 'Регистрация завершена! Теперь можно войти :)')
    return redirect('users:login')


class CustomLoginView(auth_views.LoginView):
    """Авторизация по email и паролю
    с дополнительной рекапчей после 3-го фэйла"""
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        # проверяем, отмечена ли рекапча
        marked_recaptcha = request.POST.get('g-recaptcha-response')
        if form.is_valid():
            # если рекапча отмечена
            # или ее нет (не было 3 неудачных попыток ввода логина/пароля)
            if marked_recaptcha or not request.session.get('exceeding_limit'):
                # данные из формы сохраняются в базу
                return self.form_valid(form)
        # если данные в форме неверны или не отмечена рекапча
        # форма считается невалидной
        return self.form_invalid(form)

    def form_invalid(self, form):
        # добавляем логику появления рекапчи после 3 фэйлов с логином/паролем
        # берем SessionStore object текущего запроса
        session = self.request.session
        if not session.get('failed_attempt'):
            # включаем в сессию счётчик неудачных попыток входа
            session['failed_attempt'] = 0
            # срок жизни сессии - пока у юзера не закрыт браузер
            session.set_expiry(0)
        # включаем в сессию показатель достижения лимита фэйлов
        session['exceeding_limit'] = False
        # счётчик считает фэйлы
        session['failed_attempt'] += 1
        # если фэйлов сверх лимита его показатель становится True
        if session['failed_attempt'] > 3:
            session['exceeding_limit'] = True
        # показатель достижения лимита передается логин-шаблону
        # если показатель True форма дополнится рекапчей
        return self.render_to_response(
            self.get_context_data(
                form=form,
                exceeding_limit=session['exceeding_limit'],
            )
        )


class CustomPasswordResetView(auth_views.PasswordResetView):
    """Восстановление забытого пароля через ссылку на email"""
    success_url = reverse_lazy('users:password_reset_done')


class CustomPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    success_url = reverse_lazy('users:password_reset_complete')

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>
    {% block title %}
      Доска объявлений
    {% endblock title %}
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <!-- локальный CSS -->
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
  <header>
    <!-- Fixed navbar -->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4
     mb-3 bg-white border-bottom shadow-sm">
      <a href="{% url 'board:home' %}" class="navbar-brand my-0 mr-md-auto
      font-weight-normal">
        Доска объявлений
      </a>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'board:about' %}">
          О нас
        </a>
        {% if user.is_authenticated %}
          <a class="p-2 text-dark" href="{% url 'users:logout' %}">
            Выйти
          </a>
        {% else %}
          <a class="p-2 text-dark" href="{% url 'users:login' %}">
            Войти
          </a>
          <a class="btn btn-outline-primary"
            href="{% url 'users:signup' %}">
            Зарегистрироваться
          </a>
        {% endif %}
      </nav>
    </div>
  </header>
  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>
  <!-- JavaScript -->
  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous">
  </script>
</body>
</html>

templates/about.html
{% extends '_base.html' %}

{% block title %}
  О нас
{% endblock title %}

{% block content %}
  <h1>
    О нас
  </h1>
{% endblock content %}

templates/home.html
{% extends '_base.html' %}

{% block title %}
  Главная страница
{% endblock %}

{% block content %}
{% endblock %}